import "@/styles/header.css";
import "@/styles/footer.css";
import "@/styles/reset.css";
import "@/styles/main.css";
import "@/styles/userForm.css";
import "@/styles/patient.css";
import "@/styles/pagination.css";
import "@/styles/viewerList.css";
import "@/styles/imaging-record.css";

import AppShell from "@/app/AppShell.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
    <head>
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
            integrity="sha512-papb..."
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
        />
    </head>
    <body className="layout-container">
    <AppShell>{children}</AppShell>
    </body>
    </html>
  );
}
